theme: jekyll-theme-slate
remote_theme: VNG-Realisatie/jekyll-theme-imvertor
baseurl: "/BIJ12"
# apiname: "BIJ12 documentatie"
# url: "http://localhost:4000"
nav:
  - title: Demo API
    subnav:
      - title: Main
        path: /
  - title: GitHub Pages 
    subnav:
      - title: Introductie
        path: /intro
      - title: Speciale technieken
        path: /speciale-technieken
# plugins:
#  - jekyll-redirect-from
#  - jekyll-remote-theme
github: melk-r/BIJ12
project_name: /BIJ12
